# Generated by Django 4.1.3 on 2022-12-08 15:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("auctions", "0002_comments"),
    ]

    operations = [
        migrations.RenameModel(old_name="Comments", new_name="Comment",),
    ]
