# Generated by Django 4.1.3 on 2022-12-13 10:22

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("auctions", "0004_watchlist"),
    ]

    operations = [
        migrations.AddField(
            model_name="listing",
            name="watchlist",
            field=models.ManyToManyField(
                blank=True,
                null=True,
                related_name="listingWatchlist",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.DeleteModel(name="Watchlist",),
    ]
